# Generated by Django 5.2.17 on 2026-08-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_product'),
        ('orders', '0003_remove_order_shipping_address_order_address_and_more'),
    ]

    operations = [
    ]
