# Generated by Django 5.2.17 on 2026-08-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jewelry', 'Jewelry'), ('home_decor', 'Home Decor'), ('gifts', 'Personalized Gifts'), ('artwork', 'Artwork'), ('crafts', 'Handmade Crafts'), ('accessories', 'Accessories'), ('clothing', 'Clothing'), ('stationery', 'Stationery'), ('beauty', 'Beauty & Care'), ('toys', 'Toys & Kids'), ('electronics', 'Electronics Accessories'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
