# Generated by Django 5.2.17 on 2026-08-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile Phones'), ('laptop', 'Laptops'), ('tablet', 'Tablets'), ('headphones', 'Headphones'), ('smartwatch', 'Smartwatches'), ('camera', 'Cameras'), ('television', 'Televisions'), ('speaker', 'Speakers'), ('computer_accessories', 'Computer Accessories'), ('gaming', 'Gaming Devices')], max_length=50),
        ),
    ]
