# Generated by Django 5.2.17 on 2026-08-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order_items_alter_order_name_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('headphones', 'Headphones'), ('smartwatch', 'Smartwatch'), ('camera', 'Camera'), ('television', 'Television'), ('speaker', 'Speaker'), ('computer_accessories', 'Computer Accessories'), ('gaming', 'Gaming')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
